### ISSUE TITLE
Ability to generate/calculate different prices

### ISSUE THREAD

**Issue by butenkor** [sphereio/sphere-product-mapper#11]
Assume CSV input has following data row: 

| productType | name | sku | price |
| --- | --- | --- | --- |
| myType | myName | mySku | 100 |

I would like to be able to configure 1 or more transformers which will generate following prices:

EUR 10000 DE (original price with configured currency and country)
EUR 10000 IT (original price with configured currency and country)
EUR 10000 FR (original price with configured currency and country)
EUR 7800 ALL b2b (original price minus 22% with configured currency, country and customer group)
EUR 12500 US (original price plus 25% with configured currency and country)

Desired output would be:

| productType | name | sku | price |
| --- | --- | --- | --- |
| myType | myName | mySku | EUR 10000 DE;EUR 10000 IT;EUR 10000 FR;EUR 7800 ALL b2b;EUR 12500 US |

**Comment by OlegIlyenko** [comment]
In order to implement this kind of price transformation I would need to implement some kind of definition for the transformation rules. I think it would be pretty hard to develop a set of generic rules that would be suitable for more than one use-case. 

You always  have an option to use csv-mapper as a library (and not as an application) and implement new [transformers](https://github.com/sphereio/csv-mapper/blob/master/src/coffee/transformer.coffee#L9) which will allow you to implement arbitrary logic in the value transformer.

For now I will close this issue, but if you still think that it need to be implemented in this library directly, then please feel free to reopen this issue (also in this case would be nice to have a proposition of concrete syntax definition for the price transformation rules)
